apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  annotations: 
    constraint/color : "red"
    pod/placement/cost : "10"
spec:
  selector:
    matchLabels:
        app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      schedulerName: otto
      containers:
        - name: nginx
          image: "nginx:1.11.1-alpine"
          resources:
            requests:
              cpu: "5m"
              memory: "1M"
